Amend python-validity build configuration
Building the python-validity package fails on NixOS unstable, because
the buildPythonPackage function default parameters have been changed:
"""
error: python3.13-python-validity-0.14 does not configure a `format`. To build with setuptools as before, set `pyproject = true` and `build-system = [ setuptools ]`.`
"""

See also https://nixos.org/manual/nixpkgs/unstable/#buildpythonpackage-parameters

This commit fixes that.