python-validity: fix PyPA build
Since https://github.com/NixOS/nixpkgs/pull/248866/commits/6c85fff302615c62bf4f632bca661bc48298b0a3,
buildPythonPackage uses `pypa{Build,Install}Hook` for setuptools-based
python packages rather than the older `pip{Build,Install}Hook`s.
`pypaInstallHook` appears to have more stringent testing than its
predecessor, yielding the following error:

> FileExistsError: File already exists: /nix/store/[...]-python3.10-python-validity-0.14/share/dbus-1/system.d/io.github.uunicorn.Fprint.conf

Removing the workaround doesn't appear to cause problems, and seemingly
works just fine with `pipInstallHook` as well: whatever necessitated its
addition was presumably fixed in the interim, with installation of the
resource files being silently duplicated, until now.