Upgrade to nixpkgs 23.11 (#8)
This PR upgrades the flake to nixpkgs stable 23.11.
It also contains a build fix for the python-validity package / open-fprintd package by @deviant.

These are the notes deviant provided for that fix:
> Since https://github.com/NixOS/nixpkgs/commit/6c85fff302615c62bf4f632bca661bc48298b0a3,
> buildPythonPackage uses `pypa{Build,Install}Hook` for setuptools-based
> python packages rather than the older `pip{Build,Install}Hook`s.
> `pypaInstallHook` appears to have more stringent testing than its
> predecessor, yielding the following error:
> 
> > FileExistsError: File already exists: /nix/store/[...]-python3.10-python-validity-0.14/share/dbus-1/system.d/io.github.uunicorn.Fprint.conf
>
> Removing the workaround doesn't appear to cause problems, and seemingly
> works just fine with `pipInstallHook` as well: whatever necessitated its
> addition was presumably fixed in the interim, with installation of the
> resource files being silently duplicated, until now.

fixes #7
incorporates PR #6 

---------

Co-authored-by: V <v@anomalous.eu>